version: '3.9'

services:
  consumer:
    build:
      context: .
    container_name: consumer
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/metrics
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS= 127.0.0.1:29092
    restart: always

  db:
    image: 'postgres:13-alpine'
    container_name: db
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: metrics
    restart: always

