spring:
  kafka:
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: kafka-t1:9092
#    bootstrap-servers: localhost:29092
server:
  port: 8080